version: "3.7"
services:
  db:
    hostname: db
    image: mysql
    container_name: emploiDB
    ports:
        - "3367:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: "openora"

    volumes:
        - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
        - "1001:80"
    depends_on:
        - db
    environment:
        MYSQL_ROOT_PASSWORD: "root"
        MySQL_Server: "db"



